type: dnf
repos:
  files:
    - vscode.repo
    - unityhub.repo
    - https://download.docker.com/linux/fedora/docker-ce.repo
    - https://download.opensuse.org/repositories/home:mkittler/Fedora_%OS_VERSION%/home:mkittler.repo
  keys:
    - https://packages.microsoft.com/keys/microsoft.asc
    - https://hub.unity3d.com/linux/repos/rpm/stable/repodata/repomd.xml.key
group-install:
  packages:
    - virtualization
install:
  packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

    - android-tools

    - nmap
    - wireshark

    - syncthing
    - syncthingtray
    - nextcloud-client
    
    - code
    - unityhub

    - steam
    - lutris
    - mangohud
    - goverlay
