type: default-flatpaks
configurations:
  - scope: user
    notify: false
    repo:
      url: https://apt.pop-os.org/cosmic/cosmic.flatpakrepo
      name: cosmic
      title: COSMIC
  - scope: system
    notify: false
    repo:
      url: https://apt.pop-os.org/cosmic/cosmic.flatpakrepo
      name: cosmic
      title: COSMIC
    install:
      - io.github.cosmic_utils.cosmic-ext-applet-external-monitor-brightness
