type: dnf
repos:
  files:
    - vscode.repo
    - https://download.docker.com/linux/fedora/docker-ce.repo
    - https://download.opensuse.org/repositories/home:mkittler/Fedora_%OS_VERSION%/home:mkittler.repo
  keys:
    - https://packages.microsoft.com/keys/microsoft.asc
group-install:
  packages:
    - virtualization
install:
  packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

    - syncthing
    - syncthingtray
    
    - wireshark
    - code
