name: Template - Build Image

on:
  workflow_call:
    inputs:
      pretty_name:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      recipe:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.working_directory }}/${{ inputs.recipe }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ inputs.pretty_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: blue-build/github-action@v1.10
        with:
          recipe: ${{ inputs.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number || '' }}
          working_directory: ${{ inputs.working_directory }}
          retry_push_count: 3
          verify_install: true
          maximize_build_space: true
          build_chunked_oci: true
          build_opts: --rechunk-clear-plan # Temporary fix for broken NVIDIA builds
